name: build

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'
    - '**.cshtml'
    - '**.css'

env:
  DOTNET_VERSION: '6.0.101' # The .NET SDK version to use

jobs:
  build:

    name: Build All Projects
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Build Step 1
      run: dotnet build "Tutorial/1-Create a Razor Page/RazorPagesMovie/RazorPagesMovie.csproj"

    - name: Build Step 2
      run: dotnet build "Tutorial/2-Add a model/RazorPagesMovie/RazorPagesMovie.csproj"

    - name: Build Step 3
      run: dotnet build "Tutorial/3-Update Pages/RazorPagesMovie/RazorPagesMovie.csproj"
   
    - name: Build Step 4
      run: dotnet build "Tutorial/4-Add Search/RazorPagesMovie/RazorPagesMovie.csproj"

    - name: Build Final
      run: dotnet build "Final_Project/RazorPagesMovie/RazorPagesMovie.csproj"